logging:
  level:
    root: info

---
spring:
  profiles: c1
  application:
    name: eurekaCluster1

server:
  port: 8761

eureka:
  instance:
    hostname: cluster1
  client:
    serviceUrl:
      defaultZone: http://cluster2:8762/eureka/

---
spring:
  profiles: c2
  application:
    name: eurekaCluster2
server:
  port: 8762
eureka:
  instance:
    hostname: cluster2
  client:
    serviceUrl:
      defaultZone: http://cluster1:8761/eureka/